# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='scraper_project_name',
            field=models.CharField(default=b'delcampe', max_length=100, null=True, verbose_name=b'Scraper Project Name'),
        ),
        migrations.AddField(
            model_name='scraper',
            name='spider_name',
            field=models.CharField(default=b'delcampe.net', max_length=100, null=True, verbose_name=b'Spider Name'),
        ),
    ]
